/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppFavoritesRouteImport } from './routes/_app/favorites'
import { Route as AppSearchesRouteImport } from './routes/_app/searches'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProvidersIndexRouteImport } from './routes/_app/providers/index'
import { Route as AppProvidersProviderIdRouteImport } from './routes/_app/providers/$providerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchesRoute = AppSearchesRouteImport.update({
  id: '/searches',
  path: '/searches',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersIndexRoute = AppProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersProviderIdRoute = AppProvidersProviderIdRouteImport.update({
  id: '/providers/$providerId',
  path: '/providers/$providerId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof AppFavoritesRoute
  '/searches': typeof AppSearchesRoute
  '/settings': typeof AppSettingsRoute
  '/providers/$providerId': typeof AppProvidersProviderIdRoute
  '/providers/': typeof AppProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof AppFavoritesRoute
  '/searches': typeof AppSearchesRoute
  '/settings': typeof AppSettingsRoute
  '/providers/$providerId': typeof AppProvidersProviderIdRoute
  '/providers': typeof AppProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/searches': typeof AppSearchesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/providers/$providerId': typeof AppProvidersProviderIdRoute
  '/_app/providers/': typeof AppProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/searches'
    | '/settings'
    | '/providers/$providerId'
    | '/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/searches'
    | '/settings'
    | '/providers/$providerId'
    | '/providers'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/favorites'
    | '/_app/searches'
    | '/_app/settings'
    | '/_app/providers/$providerId'
    | '/_app/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/searches': {
      id: '/_app/searches'
      path: '/searches'
      fullPath: '/searches'
      preLoaderRoute: typeof AppSearchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers/': {
      id: '/_app/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AppProvidersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers/$providerId': {
      id: '/_app/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof AppProvidersProviderIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppSearchesRoute: typeof AppSearchesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppProvidersProviderIdRoute: typeof AppProvidersProviderIdRoute
  AppProvidersIndexRoute: typeof AppProvidersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFavoritesRoute: AppFavoritesRoute,
  AppSearchesRoute: AppSearchesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppProvidersProviderIdRoute: AppProvidersProviderIdRoute,
  AppProvidersIndexRoute: AppProvidersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
